name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: download
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg
          curl -L https://youtube-dl.org/downloads/latest/youtube-dl -o ./youtube-dl
          chmod a+rx ./youtube-dl
          ./youtube-dl --config-location config.txt
      - name: Upload to WeTransfer
        id: wetransfer
        run: |
          curl -fsSL git.io/file-transfer | sh
          ./transfer wet ./downloads | tee wetransfer.log
          cat wetransfer.log | grep https
      - name: Generate Download URL
        id: tag
        run: |
          echo "::set-output name=release_tag::$(date +"%Y.%m.%d-%H%M")"
          touch release.txt
          cat wetransfer.log | grep https >> release.txt
          echo "::set-output name=status::success"
      - name: Upload URL
        uses: actions/upload-artifact@v2
        with:
          name: download.zip
          path: release.txt
